### ISSUE TITLE
EOL: move app to archived

### ISSUE THREAD

**Issue by timglaser** [newrelic/nr1-donor-analyzer#21]
## Preliminary PM work

- [x] discuss with stakeholders if this app is worth fixing and supporting, as usage is very low.
- [x] Decide if we fix this or EOL it 
- [x] If we EOL, we can document our process and use that as a test to see how hard it is to EOL a catalog app.

## APP Usage

https://staging.one.nr/0LZQW6PZkjW

### Customer Notification

from a customer POV, we'd probably want to merge a PR to the repo in question with like a banner warning about the removal of the app on x date as a heads up OR if its a small number of customers subscribed, reach out to them directly for apps that we intend to EOL of convert to experimental so people using the app are aware of the change. However in the case of this app, it's currently broken so that warning isn't necessary.

### Acceptance Criteria 

- [x] create a WIKI page on how to do EOL and move an app to experimental on the OSS Site so it's clearly documented and visible to the public
- [x] Clearly document all nuances of how you can obtain the global app UUID so you can pass that along to the Platform Team
- [x] confirm with #help-nr1-platform-services if there are any customer accounts subscribed to this app
- [x] IF so, ask if they manually (ie. go into the database) unsubscribe those accounts.
- [x] Remove this from the app catalog
- [x] Change the app OSS category to "archived"
- [x] Leave the bug unresolved for now and let someone pick it up in the community. #27

**Comment by jpvajda** [comment]
I wonder if this has something to do with the bug:

OSS/3rd-party-apps/nr1-donor-analyzer/nerdlets/shared/utils/queries.js

 On line 8 within the queries.js file, there is an TODO  

```const apdexTarget = entity.settings.apdexTarget || 0.5; // TO DO - Should we set a default value?```

**Comment by jpvajda** [comment]
For context the usage of this app is as follows: 

in the past 310 days 16 times the update Access button was clicked  triggered by 13 unique users.  Caveat, the data stopped reporting end of November.

**Comment by jpvajda** [comment]
It would be cool to try to fix this @polfliet The app is currently broken and has been for a while, it may be something the hero can pick up in Sprint 1

**Comment by jpvajda** [comment]
I'm discussing with @jaesius if this app should be supported still...

**Comment by jpvajda** [comment]
@jaesius confirmed we can:

1. remove this from the app catalog
2. change the app OSS category to "experimental"
3.  We'll leave the bug unresolved for now and let someone pick it up in the community.

**Comment by jpvajda** [comment]
@JuliaNocera  confirmed to remove the app from the catalog..

the technical process, theoretically, would be to unsubscribe all users from the nerdpack, undeploy it, and remove it from the [nr1-catalog repo in github](https://newrelic.github.io/nr1-catalog/)

**Comment by jpvajda** [comment]
More info: 

 If we are talking about a GLOBAL nerdpack, subscribed to by our customers, you'd need Nerdpack Manger permissions on the account that subscribed the nerdpack, ie. the customer account. At this point, I'd say its a topic for the Platform Services team #help-nr1-platform-services. They would probably be able to help more on
- Are there any customer accounts subscribed
- Can they manually (ie. go into the database) unsubscribe those accounts

I'd say, from a customer POV, we'd probably want to merge a PR to the repo in question with like a banner warning about the removal of the app on x date as a heads up OR if its a small number of customers subscribed, reach out to them directly for apps that we intend to EOL of convert to experimental so people using the app are aware of the change. However in the case of this app, it's currently broken so that warning isn't necessary

**Comment by jpvajda** [comment]
As part of this ticket I'd like to create a WIKI page on how to do this on the OSS Site so it's clearly documented and visible to the public

**Comment by jpvajda** [comment]
I've followed up with platform services

**Comment by jpvajda** [comment]
There seems to be some confusing on the global UUID of apps that exist in Artifact Registry 

but it sounds like it's possible to regenerate the [nr1.json](https://github.com/newrelic/nr1-tag-improver/blob/main/nr1.json#L3) file for a global app, replacing the global file with a version if you publish the app from another account that is different then the account where the app was originally created. I'm curious as to why there isn't a global identifier with the code of the app then. as we seem to be in need of referencing that when we make requests to Platform Services. --->  Should there be?

This issue has come when we requesting changes to Platform Services, we provide what we think is the correct UUID found in the existing nr1.json file to find out that actually that is not the GLOBAL identifier in Artifact Registry. 

[Graphql Query for the wrong ID](https://staging-api.newrelic.com/graphiql?#query=%7B%0A%20%20actor%20%7B%0A%20%20%20%20nr1Catalog%20%7B%0A%20%20%20%20%20%20nerdpack%28id%3A%20%2292af0365-7b3c-48f8-aecb-01fbe65f3173%22%29%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20metadata%20%7B%0A%20%20%20%20%20%20%20%20%20%20displayName%0A%20%20%20%20%20%20%20%20%20%20publishDate%0A%20%20%20%20%20%20%20%20%20%20repository%0A%20%20%20%20%20%20%20%20%20%20support%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20email%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20address%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20tagline%0A%20%20%20%20%20%20%20%20%20%20version%0A%20%20%20%20%20%20%20%20%20%20includedArtifactTypes%0A%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20additionalInfo%0A%20%20%20%20%20%20%20%20%20%20details%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

[GraphQL query for the correct ID](https://staging-api.newrelic.com/graphiql?#query=%7B%0A%20%20actor%20%7B%0A%20%20%20%20nr1Catalog%20%7B%0A%20%20%20%20%20%20nerdpack%28id%3A%20%22d5b8c492-0f3e-4686-8539-0ba2fc35ad1a%22%29%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20metadata%20%7B%0A%20%20%20%20%20%20%20%20%20%20displayName%0A%20%20%20%20%20%20%20%20%20%20publishDate%0A%20%20%20%20%20%20%20%20%20%20repository%0A%20%20%20%20%20%20%20%20%20%20support%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20email%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20address%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20tagline%0A%20%20%20%20%20%20%20%20%20%20version%0A%20%20%20%20%20%20%20%20%20%20includedArtifactTypes%0A%20%20%20%20%20%20%20%20%20%20description%0A%20%20%20%20%20%20%20%20%20%20additionalInfo%0A%20%20%20%20%20%20%20%20%20%20details%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Comment by jbeveland27** [comment]
@jpvajda Maybe this is helpful - the global UUIDs are available in the nr1-catalog repo: https://github.com/newrelic/nr1-catalog/blob/master/globals.json

Whenever a new app is added, it's UUID is added to that global file. 

All the Catalog apps are published under the `NR1 Apps` account, which is a special account that sits as a parent to every other account (and that's the mechanism by which customer accounts can self-subscribe when they add an app through the Catalog).

**Comment by jbeveland27** [comment]
Some more context - whenever an app update occurs, the UUID referenced in that globals file is copied to the nr1.json first, and then a publish occurs (that all happens in the CI workflow). That's how the UUIDs are kept in alignment. 

We don't particularly care what the UUID is in the source repo, since any user is free to pull that down and instructed (from the README) to run `nr1 nerdpack:uuid -gf` before they run the app.

**Comment by jpvajda** [comment]
@jbeveland27 this is so hopeful! I'm going to explain this in a WIKI, so I'd love for your feedback on that as we are documenting how apps can be moved from the catalog to experimental, or completely EOL'd if needed.

**Comment by jpvajda** [comment]
Wiki: https://github.com/newrelic/nr1-catalog/wiki/New-Relic-One-App-Catalog-Technical-Guide
